### ISSUE TITLE
Error in event handler: Error: Unexpected DOM. selector: "div.repository-content > div.Box > div.Box-body > table

### ISSUE THREAD

**Issue by shkomine** [arx-8/swagger-viewer#46]
@arx-8 
いつもありがたく使わせて頂いています。
以下のエラーが発生しましたので、報告させていただきます。
（issueが日本語だったので、日本語で失礼します。）

本日、Github上で利用したところ以下のエラーが発生してViewの生成に失敗しました。
おそらく、GithubのDOMに変更があったのだと思いますが、対応よろしくお願いします。

### Version
1.2.1

### Error message
`Error in event handler: Error: Unexpected DOM. selector: "div.repository-content > div.Box > div.Box-body > table"`

**Comment by arx-8** [comment]
@shkomine 
ご報告ありがとうございます！

昨日修正は完了し、
https://github.com/arx-8/swagger-viewer/pull/44

今 Chrome webstore の「審査待ち」の状態です。

まもなく修正版の `2.0.0` が配信されるかと思いますので、今しばらくお待ちください。
ご不便お掛けし申し訳ございません。

**Comment by shkomine** [comment]
@arx-8 早速のご対応ありがとうございます。
`2.0.0` の反映、楽しみにしてます！

**Comment by courtney-arnold** [comment]
@arx-8 I am having this problem as well. It appears that Github added an additional div into the hierarchy.
It is no longer
`div.repository-content > div.Box > div.Box-body > table`
It is now
`div.repository-content > div > div.Box > div.Box-body > table`

**Comment by shipleyr** [comment]
Any ideas on timelines to resolve this issue?

**Comment by courtney-arnold** [comment]
@shipleyr If you don't want to wait, you can do what I have done in the meantime. I added the tampermonkey chrome extension to my browser and then created the following script, which will remove that additional div that is causing the headache. As a note, Github is a single page application, so you will have to refresh the page with the .yaml on it, in order for the script to run. Since the script only runs upon load of the page.
`// ==UserScript==
// @name         Github Swagger Fix
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*.yaml
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    var parentDiv = document.querySelector("div.repository-content");
    var childDiv = document.querySelector("div.repository-content > div");

    while ( childDiv.hasChildNodes()){
        parentDiv.appendChild(childDiv.firstChild);
    }
})();`

**Comment by cm-kazup0n** [comment]
2.0.0 is now available in the store.
But I couldn't install the extension.

![image](https://user-images.githubusercontent.com/29879544/107336330-4e20b000-6afc-11eb-92e5-a8a4526e6309.png)

**Comment by arx-8** [comment]
@cm-kazup0n
Thank you for your report!

I have just published version `2.0.1`.
It should work this time.

---

I apologize for any inconvenience for a long time.
And Thank you for all the reports!
